export enum EventType {
  answerOffer = 'answerOffer',
  answerTrade = 'answerTrade',
  bankruptcy = 'bankruptcy',
  buildHouse = 'buildHouse',
  buyProperty = 'buyProperty',
  card = 'card',
  clearMortgage = 'clearMortgage',
  freeParking = 'freeParking',
  getOutOfJail = 'getOutOfJail',
  goToJail = 'goToJail',
  mortgage = 'mortgage',
  passGo = 'passGo',
  payRent = 'payRent',
  payTax = 'payTax',
  playerExit = 'playerExit',
  sellHouse = 'sellHouse',
  turnInJail = 'turnInJail',
}
