export enum OnlineErrorCodes {
  DUPLICATE_PLAYER_NAME = 'DUPLICATE_PLAYER_NAME',
  GAME_ALREADY_STARTED = 'GAME_ALREADY_STARTED',
  INVALID_PLAYER_TOKEN = 'INVALID_PLAYER_TOKEN',
  INVALID_ROOM_ID = 'INVALID_ROOM_ID',
  MISSING_PLAYER_NAME = 'MISSING_PLAYER_NAME',
  NOT_YOUR_TURN = 'NOT_YOUR_TURN',
}
