import { Neighborhood, PropertyType, SquareType, TaxType } from '../../enums';
import { Id, Square } from '../../types';

export const squaresMap: { [key: Id]: Square } = {
  1: { id: 1, name: 'Go', type: SquareType.go },
  2: {
    id: 2,
    name: 'Old Kent Rd.',
    neighborhood: Neighborhood.brown,
    price: 60,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  3: { id: 3, name: 'Community chest', type: SquareType.communityChest },
  4: {
    id: 4,
    name: 'Whitechapel Rd.',
    neighborhood: Neighborhood.brown,
    price: 60,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  5: {
    id: 5,
    name: 'Income Tax',
    taxType: TaxType.income,
    type: SquareType.tax,
  },
  6: {
    id: 6,
    name: 'Kings Cross',
    price: 200,
    propertyType: PropertyType.station,
    type: SquareType.property,
  },
  7: {
    id: 7,
    name: 'Angel Islington',
    neighborhood: Neighborhood.lightblue,
    price: 100,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  8: { id: 8, name: 'Chance', type: SquareType.chance },
  9: {
    id: 9,
    name: 'Euston Rd.',
    neighborhood: Neighborhood.lightblue,
    price: 100,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  10: {
    id: 10,
    name: 'Pentonville Rd.',
    neighborhood: Neighborhood.lightblue,
    price: 120,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  11: { id: 11, name: 'Jail', type: SquareType.jail },
  12: {
    id: 12,
    name: 'Pall Mall',
    neighborhood: Neighborhood.pink,
    price: 140,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  13: {
    icon: '🔌',
    id: 13,
    name: 'Electric Co.',
    price: 150,
    propertyType: PropertyType.utility,
    type: SquareType.property,
  },
  14: {
    id: 14,
    name: 'Whitehall',
    neighborhood: Neighborhood.pink,
    price: 140,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  15: {
    id: 15,
    name: 'Northumberland',
    neighborhood: Neighborhood.pink,
    price: 160,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  16: {
    id: 16,
    name: 'Marylebone',
    price: 200,
    propertyType: PropertyType.station,
    type: SquareType.property,
  },
  17: {
    id: 17,
    name: 'Bow St.',
    neighborhood: Neighborhood.orange,
    price: 180,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  18: { id: 18, name: 'Community chest', type: SquareType.communityChest },
  19: {
    id: 19,
    name: 'Marlborough St.',
    neighborhood: Neighborhood.orange,
    price: 180,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  20: {
    id: 20,
    name: 'Vine St.',
    neighborhood: Neighborhood.orange,
    price: 200,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  21: { id: 21, name: 'Free Parking', type: SquareType.parking },
  22: {
    id: 22,
    name: 'Strand',
    neighborhood: Neighborhood.red,
    price: 220,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  23: { id: 23, name: 'Chance', type: SquareType.chance },
  24: {
    id: 24,
    name: 'Fleet St.',
    neighborhood: Neighborhood.red,
    price: 220,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  25: {
    id: 25,
    name: 'Trafalgar Square',
    neighborhood: Neighborhood.red,
    price: 240,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  26: {
    id: 26,
    name: 'Fenchurch St.',
    price: 200,
    propertyType: PropertyType.station,
    type: SquareType.property,
  },
  27: {
    id: 27,
    name: 'Leicester Square',
    neighborhood: Neighborhood.yellow,
    price: 260,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  28: {
    id: 28,
    name: 'Coventry St.',
    neighborhood: Neighborhood.yellow,
    price: 260,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  29: {
    icon: '💧',
    id: 29,
    name: 'Water Works',
    price: 150,
    propertyType: PropertyType.utility,
    type: SquareType.property,
  },
  30: {
    id: 30,
    name: 'Piccadilly',
    neighborhood: Neighborhood.yellow,
    price: 280,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  31: { id: 31, name: 'Go To Jail', type: SquareType.goToJail },
  32: {
    id: 32,
    name: 'Regent St.',
    neighborhood: Neighborhood.green,
    price: 300,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  33: {
    id: 33,
    name: 'Oxford St.',
    neighborhood: Neighborhood.green,
    price: 300,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  34: { id: 34, name: 'Community chest', type: SquareType.communityChest },
  35: {
    id: 35,
    name: 'Bond St.',
    neighborhood: Neighborhood.green,
    price: 320,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  36: {
    id: 36,
    name: 'Liverpool St.',
    price: 200,
    propertyType: PropertyType.station,
    type: SquareType.property,
  },
  37: { id: 37, name: 'Chance', type: SquareType.chance },
  38: {
    id: 38,
    name: 'Park Lane',
    neighborhood: Neighborhood.darkblue,
    price: 350,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  39: {
    id: 39,
    name: 'Luxury Tax',
    taxType: TaxType.luxury,
    type: SquareType.tax,
  },
  40: {
    id: 40,
    name: 'Mayfair',
    neighborhood: Neighborhood.darkblue,
    price: 400,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
};
