export enum ChangeType {
  answerOffer = 'answerOffer',
  bankruptcy = 'bankruptcy',
  buildHouse = 'buildHouse',
  buyProperty = 'buyProperty',
  chance = 'chance',
  clearMortgage = 'clearMortgage',
  communityChest = 'communityChest',
  freeParking = 'freeParking',
  getOutOfJail = 'getOutOfJail',
  goToJail = 'goToJail',
  mortgage = 'mortgage',
  passGo = 'passGo',
  payRent = 'payRent',
  payTax = 'payTax',
  placeOffer = 'placeOffer',
  playerWin = 'playerWin',
  remainInJail = 'remainInJail',
  rollDice = 'rollDice',
  sellHouse = 'sellHouse',
}
