export enum GameEventType {
  bankruptcy = 'bankruptcy',
  buyProperty = 'buyProperty',
  chance = 'chance',
  communityChest = 'communityChest',
  endTurn = 'endTurn',
  freeParking = 'freeParking',
  getsOutOfJail = 'getsOutOfJail',
  goToJail = 'goToJail',
  passGo = 'passGo',
  payRent = 'payRent',
  payTax = 'payTax',
  playerWins = 'playerWins',
  remainsInJail = 'remainsInJail',
  rollDice = 'rollDice',
}
