export enum GameEventType {
  bankruptcy = 'bankruptcy',
  buyProperty = 'buyProperty',
  chance = 'chance',
  clearMortgage = 'clearMortgage',
  communityChest = 'communityChest',
  freeParking = 'freeParking',
  getOutOfJail = 'getOutOfJail',
  goToJail = 'goToJail',
  mortgage = 'mortgage',
  passGo = 'passGo',
  payRent = 'payRent',
  payTax = 'payTax',
  playerWin = 'playerWin',
  remainInJail = 'remainInJail',
  rollDice = 'rollDice',
}
