import { PropertyType, SquareType, TurnPhase } from '../enums';
import { PlayerStatus } from '../enums/player-status';
import { playerInitialMoney } from '../parameters';
import { Square } from '../types';
import { Game } from '../types/game';

export const createGame = (nPlayers: number): Game => {
  const squares: Square[] = [
    { name: 'Go', type: SquareType.go },
    {
      name: 'Old Kent Road',
      type: SquareType.property,
      propertyType: PropertyType.street,
      group: 'brown',
      price: 60,
    },
    { name: 'Chest', type: SquareType.chest },
    {
      name: 'Whitechapel Road',
      type: SquareType.property,
      propertyType: PropertyType.street,
      group: 'brown',
      price: 60,
    },
    { name: 'Income Tax', type: SquareType.tax },
    {
      name: 'Kings Cross Station',
      type: SquareType.property,
      propertyType: PropertyType.station,
      price: 200,
    },
    {
      name: 'The Angel Islington',
      type: SquareType.property,
      propertyType: PropertyType.street,
      group: 'lightblue',
      price: 100,
    },
    { name: 'Chest', type: SquareType.chest },
    {
      name: 'Euston Road',
      type: SquareType.property,
      propertyType: PropertyType.street,
      group: 'lightblue',
      price: 100,
    },
    {
      name: 'Pentonville Road',
      type: SquareType.property,
      propertyType: PropertyType.street,
      group: 'lightblue',
      price: 120,
    },
    { name: 'Jail', type: SquareType.jail },
    {
      name: 'Pall Mall',
      type: SquareType.property,
      propertyType: PropertyType.street,
      group: 'pink',
      price: 140,
    },
    {
      name: 'Electric Company',
      type: SquareType.property,
      propertyType: PropertyType.power,
      price: 150,
    },
    {
      name: 'Whitehall',
      type: SquareType.property,
      propertyType: PropertyType.street,
      group: 'pink',
      price: 140,
    },
    {
      name: 'Northumberland Avenue',
      type: SquareType.property,
      propertyType: PropertyType.street,
      group: 'pink',
      price: 160,
    },
    {
      name: 'Marylebone Station',
      type: SquareType.property,
      propertyType: PropertyType.station,
      price: 200,
    },
    {
      name: 'Bow Street',
      type: SquareType.property,
      propertyType: PropertyType.street,
      group: 'orange',
      price: 180,
    },
    { name: 'Chest', type: SquareType.chest },
    {
      name: 'Marlborough Street',
      type: SquareType.property,
      propertyType: PropertyType.street,
      group: 'orange',
      price: 180,
    },
    {
      name: 'Vine Street',
      type: SquareType.property,
      propertyType: PropertyType.street,
      group: 'orange',
      price: 200,
    },
    { name: 'Free Parking', type: SquareType.parking },
    {
      name: 'Strand',
      type: SquareType.property,
      propertyType: PropertyType.street,
      group: 'red',
      price: 220,
    },
    { name: 'Chest', type: SquareType.chest },
    {
      name: 'Fleet Street',
      type: SquareType.property,
      propertyType: PropertyType.street,
      group: 'red',
      price: 220,
    },
    {
      name: 'Trafalgar Square',
      type: SquareType.property,
      propertyType: PropertyType.street,
      group: 'red',
      price: 240,
    },
    {
      name: 'Fenchurch St. Station',
      type: SquareType.property,
      propertyType: PropertyType.station,
      price: 200,
    },
    {
      name: 'Leicester Square',
      type: SquareType.property,
      propertyType: PropertyType.street,
      group: 'yellow',
      price: 260,
    },
    {
      name: 'Coventry Street',
      type: SquareType.property,
      propertyType: PropertyType.street,
      group: 'yellow',
      price: 260,
    },
    {
      name: 'Water Works',
      type: SquareType.property,
      propertyType: PropertyType.power,
      price: 150,
    },
    {
      name: 'Piccadilly',
      type: SquareType.property,
      propertyType: PropertyType.street,
      group: 'yellow',
      price: 280,
    },
    { name: 'Go To Jail', type: SquareType.goToJail },
    {
      name: 'Regent Street',
      type: SquareType.property,
      propertyType: PropertyType.street,
      group: 'green',
      price: 300,
    },
    {
      name: 'Oxford Street',
      type: SquareType.property,
      propertyType: PropertyType.street,
      group: 'green',
      price: 300,
    },
    { name: 'Chest', type: SquareType.chest },
    {
      name: 'Bond Street',
      type: SquareType.property,
      propertyType: PropertyType.street,
      group: 'green',
      price: 320,
    },
    {
      name: 'Liverpool St. Station',
      type: SquareType.property,
      propertyType: PropertyType.station,
      price: 200,
    },
    { name: 'Chest', type: SquareType.chest },
    {
      name: 'Park Lane',
      type: SquareType.property,
      propertyType: PropertyType.street,
      group: 'darkblue',
      price: 350,
    },
    { name: 'Super Tax', type: SquareType.tax },
    {
      name: 'Mayfair',
      type: SquareType.property,
      propertyType: PropertyType.street,
      group: 'darkblue',
      price: 400,
    },
  ];

  return {
    currentPlayerId: 0,
    players: [...Array(nPlayers)].map((_, index) => ({
      color: '#' + ((Math.random() * 0xffffff) << 0).toString(16).padStart(6, '0'),
      id: index,
      money: playerInitialMoney,
      name: `Player ${index + 1}`,
      position: 0,
      properties: [],
      status: PlayerStatus.playing,
    })),
    squares,
    events: [],
    turnPhase: TurnPhase.start,
  };
};
