import { GamePhase, Neighborhood, PropertyType, SquareType, TaxType } from '../enums';
import { PlayerStatus } from '../enums/player-status';
import { playerInitialMoney } from '../parameters';
import { Player, Square } from '../types';
import { Game } from '../types/game';

const squares: Square[] = [
  { id: 1, name: 'Go', type: SquareType.go },
  {
    id: 2,
    name: 'Old Kent Rd.',
    neighborhood: Neighborhood.brown,
    price: 60,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  { id: 3, name: 'Community chest', type: SquareType.communityChest },
  {
    id: 4,
    name: 'Whitechapel Rd.',
    neighborhood: Neighborhood.brown,
    price: 60,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  {
    id: 5,
    name: 'Income Tax',
    taxType: TaxType.income,
    type: SquareType.tax,
  },
  {
    id: 6,
    name: 'Kings Cross',
    price: 200,
    propertyType: PropertyType.station,
    type: SquareType.property,
  },
  {
    id: 7,
    name: 'Angel Islington',
    neighborhood: Neighborhood.lightblue,
    price: 100,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  { id: 8, name: 'Chance', type: SquareType.chance },
  {
    id: 9,
    name: 'Euston Rd.',
    neighborhood: Neighborhood.lightblue,
    price: 100,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  {
    id: 10,
    name: 'Pentonville Rd.',
    neighborhood: Neighborhood.lightblue,
    price: 120,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  { id: 11, name: 'Jail', type: SquareType.jail },
  {
    id: 12,
    name: 'Pall Mall',
    neighborhood: Neighborhood.pink,
    price: 140,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  {
    id: 13,
    name: 'Electric Co.',
    price: 150,
    propertyType: PropertyType.utility,
    type: SquareType.property,
  },
  {
    id: 14,
    name: 'Whitehall',
    neighborhood: Neighborhood.pink,
    price: 140,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  {
    id: 15,
    name: 'Northumberland',
    neighborhood: Neighborhood.pink,
    price: 160,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  {
    id: 16,
    name: 'Marylebone',
    price: 200,
    propertyType: PropertyType.station,
    type: SquareType.property,
  },
  {
    id: 17,
    name: 'Bow St.',
    neighborhood: Neighborhood.orange,
    price: 180,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  { id: 18, name: 'Community chest', type: SquareType.communityChest },
  {
    id: 19,
    name: 'Marlborough St.',
    neighborhood: Neighborhood.orange,
    price: 180,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  {
    id: 20,
    name: 'Vine St.',
    neighborhood: Neighborhood.orange,
    price: 200,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  { id: 21, name: 'Free Parking', type: SquareType.parking },
  {
    id: 22,
    name: 'Strand',
    neighborhood: Neighborhood.red,
    price: 220,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  { id: 23, name: 'Chance', type: SquareType.chance },
  {
    id: 24,
    name: 'Fleet St.',
    neighborhood: Neighborhood.red,
    price: 220,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  {
    id: 25,
    name: 'Trafalgar Square',
    neighborhood: Neighborhood.red,
    price: 240,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  {
    id: 26,
    name: 'Fenchurch St.',
    price: 200,
    propertyType: PropertyType.station,
    type: SquareType.property,
  },
  {
    id: 27,
    name: 'Leicester Square',
    neighborhood: Neighborhood.yellow,
    price: 260,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  {
    id: 28,
    name: 'Coventry St.',
    neighborhood: Neighborhood.yellow,
    price: 260,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  {
    id: 29,
    name: 'Water Works',
    price: 150,
    propertyType: PropertyType.utility,
    type: SquareType.property,
  },
  {
    id: 30,
    name: 'Piccadilly',
    neighborhood: Neighborhood.yellow,
    price: 280,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  { id: 31, name: 'Go To Jail', type: SquareType.goToJail },
  {
    id: 32,
    name: 'Regent St.',
    neighborhood: Neighborhood.green,
    price: 300,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  {
    id: 33,
    name: 'Oxford St.',
    neighborhood: Neighborhood.green,
    price: 300,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  { id: 34, name: 'Community chest', type: SquareType.communityChest },
  {
    id: 35,
    name: 'Bond St.',
    neighborhood: Neighborhood.green,
    price: 320,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  {
    id: 36,
    name: 'Liverpool St.',
    price: 200,
    propertyType: PropertyType.station,
    type: SquareType.property,
  },
  { id: 37, name: 'Chance', type: SquareType.chance },
  {
    id: 38,
    name: 'Park Lane',
    neighborhood: Neighborhood.darkblue,
    price: 350,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
  {
    id: 39,
    name: 'Luxury Tax',
    taxType: TaxType.luxury,
    type: SquareType.tax,
  },
  {
    id: 40,
    name: 'Mayfair',
    neighborhood: Neighborhood.darkblue,
    price: 400,
    propertyType: PropertyType.street,
    type: SquareType.property,
  },
];

export const createGame = (nPlayers: number): Game => {
  const players = [...Array(nPlayers)].map<Player>((_, index) => ({
    color: '#' + ((Math.random() * 0xffffff) << 0).toString(16).padStart(6, '0'),
    id: index + 1,
    money: playerInitialMoney,
    name: `Player ${index + 1}`,
    properties: [],
    squareId: squares[0].id,
    status: PlayerStatus.playing,
    turnsInJail: 0,
  }));

  return {
    centerPot: 0,
    currentPlayerId: players[0].id,
    dice: [],
    events: [],
    gamePhase: GamePhase.rollDice,
    modals: [],
    players,
    squares,
    toasts: [],
  };
};
