import { PropertyType, SquareType, TurnPhase } from '../enums';
import { PlayerStatus } from '../enums/player-status';
import { playerInitialMoney } from '../parameters';
import { Square } from '../types';
import { Game } from '../types/game';

export const createGame = (nPlayers: number): Game => {
  const squares: Square[] = [
    { name: 'Go', type: SquareType.go },
    {
      name: 'Old Kent Rd.',
      type: SquareType.property,
      propertyType: PropertyType.street,
      color: 'brown',
      textColor: 'white',
      price: 60,
    },
    { name: 'Chest', type: SquareType.chest },
    {
      name: 'Whitechapel Rd.',
      type: SquareType.property,
      propertyType: PropertyType.street,
      color: 'brown',
      textColor: 'white',
      price: 60,
    },
    { name: 'Income Tax', type: SquareType.tax },
    {
      name: 'Kings Cross',
      type: SquareType.property,
      propertyType: PropertyType.station,
      price: 200,
    },
    {
      name: 'Angel Islington',
      type: SquareType.property,
      propertyType: PropertyType.street,
      color: 'lightblue',
      textColor: 'black',
      price: 100,
    },
    { name: 'Chest', type: SquareType.chest },
    {
      name: 'Euston Rd.',
      type: SquareType.property,
      propertyType: PropertyType.street,
      color: 'lightblue',
      textColor: 'black',
      price: 100,
    },
    {
      name: 'Pentonville Rd.',
      type: SquareType.property,
      propertyType: PropertyType.street,
      color: 'lightblue',
      textColor: 'black',
      price: 120,
    },
    { name: 'Jail', type: SquareType.jail },
    {
      name: 'Pall Mall',
      type: SquareType.property,
      propertyType: PropertyType.street,
      color: 'pink',
      textColor: 'black',
      price: 140,
    },
    {
      name: 'Electric Co.',
      type: SquareType.property,
      propertyType: PropertyType.power,
      price: 150,
    },
    {
      name: 'Whitehall',
      type: SquareType.property,
      propertyType: PropertyType.street,
      color: 'pink',
      textColor: 'black',
      price: 140,
    },
    {
      name: 'Northumberland',
      type: SquareType.property,
      propertyType: PropertyType.street,
      color: 'pink',
      textColor: 'black',
      price: 160,
    },
    {
      name: 'Marylebone',
      type: SquareType.property,
      propertyType: PropertyType.station,
      price: 200,
    },
    {
      name: 'Bow St.',
      type: SquareType.property,
      propertyType: PropertyType.street,
      color: 'orange',
      textColor: 'white',
      price: 180,
    },
    { name: 'Chest', type: SquareType.chest },
    {
      name: 'Marlborough St.',
      type: SquareType.property,
      propertyType: PropertyType.street,
      color: 'orange',
      textColor: 'white',
      price: 180,
    },
    {
      name: 'Vine St.',
      type: SquareType.property,
      propertyType: PropertyType.street,
      color: 'orange',
      textColor: 'white',
      price: 200,
    },
    { name: 'Free Parking', type: SquareType.parking },
    {
      name: 'Strand',
      type: SquareType.property,
      propertyType: PropertyType.street,
      color: 'red',
      textColor: 'white',
      price: 220,
    },
    { name: 'Chest', type: SquareType.chest },
    {
      name: 'Fleet St.',
      type: SquareType.property,
      propertyType: PropertyType.street,
      color: 'red',
      textColor: 'white',
      price: 220,
    },
    {
      name: 'Trafalgar Square',
      type: SquareType.property,
      propertyType: PropertyType.street,
      color: 'red',
      textColor: 'white',
      price: 240,
    },
    {
      name: 'Fenchurch St.',
      type: SquareType.property,
      propertyType: PropertyType.station,
      price: 200,
    },
    {
      name: 'Leicester Square',
      type: SquareType.property,
      propertyType: PropertyType.street,
      color: 'yellow',
      textColor: 'black',
      price: 260,
    },
    {
      name: 'Coventry St.',
      type: SquareType.property,
      propertyType: PropertyType.street,
      color: 'yellow',
      textColor: 'black',
      price: 260,
    },
    {
      name: 'Water Works',
      type: SquareType.property,
      propertyType: PropertyType.power,
      price: 150,
    },
    {
      name: 'Piccadilly',
      type: SquareType.property,
      propertyType: PropertyType.street,
      color: 'yellow',
      textColor: 'black',
      price: 280,
    },
    { name: 'Go To Jail', type: SquareType.goToJail },
    {
      name: 'Regent St.',
      type: SquareType.property,
      propertyType: PropertyType.street,
      color: 'green',
      textColor: 'white',
      price: 300,
    },
    {
      name: 'Oxford St.',
      type: SquareType.property,
      propertyType: PropertyType.street,
      color: 'green',
      textColor: 'white',
      price: 300,
    },
    { name: 'Chest', type: SquareType.chest },
    {
      name: 'Bond St.',
      type: SquareType.property,
      propertyType: PropertyType.street,
      color: 'green',
      textColor: 'white',
      price: 320,
    },
    {
      name: 'Liverpool St.',
      type: SquareType.property,
      propertyType: PropertyType.station,
      price: 200,
    },
    { name: 'Chest', type: SquareType.chest },
    {
      name: 'Park Lane',
      type: SquareType.property,
      propertyType: PropertyType.street,
      color: 'darkblue',
      textColor: 'white',
      price: 350,
    },
    { name: 'Super Tax', type: SquareType.tax },
    {
      name: 'Mayfair',
      type: SquareType.property,
      propertyType: PropertyType.street,
      color: 'darkblue',
      textColor: 'white',
      price: 400,
    },
  ];

  return {
    currentPlayerId: 0,
    players: [...Array(nPlayers)].map((_, index) => ({
      color: '#' + ((Math.random() * 0xffffff) << 0).toString(16).padStart(6, '0'),
      id: index,
      money: playerInitialMoney,
      name: `Player ${index + 1}`,
      position: 0,
      properties: [],
      status: PlayerStatus.playing,
    })),
    squares: squares.map((s, index) => ({ ...s, position: index })),
    events: [],
    turnPhase: TurnPhase.start,
  };
};
