export enum GamePhase {
  answerOffer = 'answerOffer',
  answerTrade = 'answerTrade',
  applyCard = 'applyCard',
  avatarAnimation = 'avatarAnimation',
  buyProperty = 'buyProperty',
  buyingLiquidation = 'buyingLiquidation',
  cannotPay = 'cannotPay',
  diceAnimation = 'diceAnimation',
  diceInJailAnimation = 'diceInJailAnimation',
  drawCard = 'drawCard',
  jailNotification = 'jailNotification',
  jailOptions = 'jailOptions',
  outOfJailAnimation = 'outOfJailAnimation',
  paymentLiquidation = 'paymentLiquidation',
  play = 'play',
  playerWins = 'playerWins',
  rollDice = 'rollDice',
  trade = 'trade',
}
