export enum GamePhase {
  answerOffer = 'answerOffer',
  answerTrade = 'answerTrade',
  applyCard = 'applyCard',
  buyProperty = 'buyProperty',
  buyPropertyLiquidation = 'buyPropertyLiquidation',
  cannotPay = 'cannotPay',
  diceAnimation = 'diceAnimation',
  diceInJailAnimation = 'diceInJailAnimation',
  drawCard = 'drawCard',
  goToJail = 'goToJail',
  jailOptions = 'jailOptions',
  outOfJailAnimation = 'outOfJailAnimation',
  pendingPaymentLiquidation = 'pendingPaymentLiquidation',
  play = 'play',
  playerAnimation = 'playerAnimation',
  playerWins = 'playerWins',
  rollDice = 'rollDice',
  trade = 'trade',
}
